apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-sample
  name: java-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-sample
    spec:
      containers:
      - image: rajkumaraute/java-sample
        name: java-sample
        resources: {}
status: {}
